import Header from "@/components/Header";
import "./globals.css";
import { Tiro_Bangla } from 'next/font/google';
import BackToTopButton from "./BackToTopButton";
import Footer from "@/components/Footer";
import ScrollToTop from "@/components/ScrollToTop";
const tiroBangla = Tiro_Bangla({
  variable: "--font-tiro-bangla",
  subsets: ["bengali"],
  weight: ["400"],
});

export const metadata = {
  metadataBase: new URL("http://localhost:3000"), // change to production URL
  title: "News Portal",
  description: "Generated by create next app",
  robots: "noindex, nofollow",
  openGraph: {
    images: [
      {
        url: "/logo-fb.jpg",
        width: 800,
        height: 420,
      },
    ],
  },
  icons: {
    icon: "/favicon.ico",
  },
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({ children }) {
  return (
    <html lang="bn" className={`${tiroBangla.variable}`}>
      <head>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" />
      </head>
      <body>
        <Header />
        <ScrollToTop />
        {children}

        <Footer />
        <BackToTopButton />
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.min.js"
          integrity="sha384-RuyvpeZCxMJCqVUGFI0Do1mQrods/hhxYlcVfGPOfQtPJh0JCw12tUAZ/Mv10S7D"
          crossOrigin="anonymous"
        ></script>
        <script
          src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
          integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
          crossOrigin="anonymous"
        ></script>
      </body>
    </html>
  );
}
